import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { InstallHooksContext } from "./setup";

const CLAUDE_SETTINGS_REL = join(".claude", "settings.json");
const CODEX_HOOKS_REL = join(".codex", "hooks", "codogotchi.toml");

function getUserRoot(): string {
	const override = process.env.CODOGOTCHI_USER_ROOT;
	if (override && override.length > 0) return override;
	return homedir();
}

type ClaudeHookEntry = { type: "command"; command: string };
type ClaudeHookMatcher = { matcher: string; hooks: ClaudeHookEntry[] };
type ClaudeHookSlot = ClaudeHookMatcher[];
type ClaudeHooks = Record<string, ClaudeHookSlot | unknown>;
type ClaudeSettings = {
	hooks?: ClaudeHooks;
} & Record<string, unknown>;

/// The command Claude Code spawns. Re-used to detect (and dedupe) prior
/// codogotchi entries so re-running setup is idempotent.
const CODOGOTCHI_COMMAND = "codogotchi-hook";

/// Claude Code event slots the hook is registered against. `PreToolUse` fires
/// on every tool invocation; `Stop` fires when Claude finishes a turn. Between
/// them the hook sees enough lifecycle traffic to drive the menubar pet's
/// `activity_state` without overlapping into Codex's hook surface.
const CODOGOTCHI_EVENTS = ["PreToolUse", "Stop"] as const;

async function readJsonOrEmpty<T extends object>(path: string): Promise<T> {
	try {
		const raw = await readFile(path, "utf8");
		const parsed = JSON.parse(raw);
		if (parsed && typeof parsed === "object") return parsed as T;
		return {} as T;
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === "ENOENT") return {} as T;
		throw err;
	}
}

async function writeText(path: string, content: string): Promise<void> {
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, content, "utf8");
}

function isHookMatcher(value: unknown): value is ClaudeHookMatcher {
	if (!value || typeof value !== "object") return false;
	const v = value as Record<string, unknown>;
	return typeof v.matcher === "string" && Array.isArray(v.hooks);
}

/// Replace any existing codogotchi-hook matcher in `slot` with a canonical
/// matcher-`""` entry. Unrelated matchers (e.g. a user's `Read`-scoped
/// read-once hook) are left untouched. The filter+append shape keeps the
/// installer idempotent: re-running produces a byte-identical file.
function withCodogotchiMatcher(slot: ClaudeHookSlot): ClaudeHookSlot {
	const others = slot.filter(
		(m) => !m.hooks.some((h) => h.command === CODOGOTCHI_COMMAND),
	);
	others.push({
		matcher: "",
		hooks: [{ type: "command", command: CODOGOTCHI_COMMAND }],
	});
	return others;
}

// installHooks writes the hook config entries that invoke the
// `codogotchi-hook` binary into both Claude Code's `settings.json` and
// Codex's `~/.codex/hooks/codogotchi.toml`. The binary itself ships under
// `packages/cli/bin/`. Re-running setup is idempotent: identical config
// produces identical files.
export async function installHooks(ctx: InstallHooksContext): Promise<void> {
	const root = getUserRoot();

	const claudePath = join(root, CLAUDE_SETTINGS_REL);
	const claudeSettings = await readJsonOrEmpty<ClaudeSettings>(claudePath);

	// Strip the legacy `hooks.codogotchi` orphan written by P1.12-era
	// installs. Claude Code routes hooks by event name keys (`PreToolUse`,
	// `Stop`, ...), not by a top-level `codogotchi` key, so the legacy
	// entry was inert and never fired. Removing it on every install lets
	// existing users converge onto the correct wiring without manual edits.
	const existing = (claudeSettings.hooks ?? {}) as ClaudeHooks;
	const { codogotchi: _legacy, ...preserved } = existing as Record<
		string,
		unknown
	>;

	const nextHooks: ClaudeHooks = { ...(preserved as ClaudeHooks) };
	for (const event of CODOGOTCHI_EVENTS) {
		const raw = nextHooks[event];
		const slot: ClaudeHookSlot = Array.isArray(raw)
			? raw.filter(isHookMatcher)
			: [];
		nextHooks[event] = withCodogotchiMatcher(slot);
	}
	claudeSettings.hooks = nextHooks;

	await writeText(claudePath, `${JSON.stringify(claudeSettings, null, 2)}\n`);

	const codexPath = join(root, CODEX_HOOKS_REL);
	// JSON.stringify produces a valid double-quoted string literal — escaping
	// any " or \ — that is also a valid TOML basic string. This keeps the file
	// well-formed even if CODOGOTCHI_HOME or the Convex URL contains those.
	const codexToml = [
		"# codogotchi: lifecycle hook configuration",
		"# Re-generated by `codogotchi setup`. The binary lands in P1.18.",
		'name = "codogotchi"',
		'command = "codogotchi-hook"',
		"",
		"[env]",
		`CODOGOTCHI_HOME = ${JSON.stringify(ctx.home)}`,
		`CODOGOTCHI_CONVEX_URL = ${JSON.stringify(ctx.convex_http_url)}`,
		"",
	].join("\n");
	await writeText(codexPath, codexToml);
}
