import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { InstallHooksContext } from "./setup";

const CLAUDE_SETTINGS_REL = join(".claude", "settings.json");
const CODEX_HOOKS_REL = join(".codex", "hooks", "codogotchi.toml");

function getUserRoot(): string {
	const override = process.env.CODOGOTCHI_USER_ROOT;
	if (override && override.length > 0) return override;
	return homedir();
}

type ClaudeSettings = {
	hooks?: Record<string, unknown>;
} & Record<string, unknown>;

async function readJsonOrEmpty<T extends object>(path: string): Promise<T> {
	try {
		const raw = await readFile(path, "utf8");
		const parsed = JSON.parse(raw);
		if (parsed && typeof parsed === "object") return parsed as T;
		return {} as T;
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === "ENOENT") return {} as T;
		throw err;
	}
}

async function writeText(path: string, content: string): Promise<void> {
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, content, "utf8");
}

// Phase 01 installHooks writes only the hook *config entries* invoking the
// `codogotchi-hook` binary. The binary itself lands in P1.18. Re-running setup
// is idempotent: identical config produces identical files.
export async function installHooks(ctx: InstallHooksContext): Promise<void> {
	const root = getUserRoot();

	const claudePath = join(root, CLAUDE_SETTINGS_REL);
	const claudeSettings = await readJsonOrEmpty<ClaudeSettings>(claudePath);
	claudeSettings.hooks = {
		...(claudeSettings.hooks ?? {}),
		codogotchi: {
			command: "codogotchi-hook",
			env: {
				CODOGOTCHI_HOME: ctx.home,
				CODOGOTCHI_CONVEX_URL: ctx.convex_http_url,
			},
		},
	};
	await writeText(claudePath, `${JSON.stringify(claudeSettings, null, 2)}\n`);

	const codexPath = join(root, CODEX_HOOKS_REL);
	const codexToml = [
		"# codogotchi: lifecycle hook configuration",
		"# Re-generated by `codogotchi setup`. The binary lands in P1.18.",
		'name = "codogotchi"',
		'command = "codogotchi-hook"',
		"",
		"[env]",
		`CODOGOTCHI_HOME = "${ctx.home}"`,
		`CODOGOTCHI_CONVEX_URL = "${ctx.convex_http_url}"`,
		"",
	].join("\n");
	await writeText(codexPath, codexToml);
}
